/** All public copy, assets, fundraising data and destinations live here.
 * Draft copy is a starting point for Justin to approve. No patient history is implied.
 */
export const site = {
  name: "Justin Liang",
  initials: "JL",
  brand: "A little hope. A lot of heart.",
  memberLabel: "Phoenix Children’s Teen Council",
  independentLabel: "A personal fundraiser by Justin Liang",
  donationUrl: "https://ignitehope.phoenixchildrensfoundation.org/justin-liang",
  canonicalUrl: "https://my-pch-website.vercel.app",
  metadata: {
    title: "Justin Liang • A little hope. A lot of heart.",
    description: "Help Justin Liang support Phoenix Children’s through the Teen Council. Read his why, share the cause, and donate on the official fundraising platform.",
  },
  navigation: [{ label: "Justin’s message", href: "#my-message" }, { label: "My why", href: "#my-why" }, { label: "Share", href: "#share" }],
  labels: {
    donate: "Donate through Phoenix Children’s",
    donateShort: "Donate",
    why: "Why I’m Doing This",
    secure: "Donations are processed securely through Phoenix Children’s.",
    skip: "Skip to content",
    external: "Opens in a new tab",
    backToTop: "Back to top",
  },
  hero: {
    video: {
      src: "/videos/hero-captioned-desktop.mp4",
      mobileSrc: "/videos/hero-captioned-mobile.mp4",
      label: "Fundraising campaign hero video",
      poster: "/images/hero-poster.jpg",
      fallback: "Watch the hero video",
    },
    eyebrow: "Young voices. Real possibility.",
    headline: "Help me support Phoenix Children’s.",
    watchMessage: "Watch my 1-minute message",
    accent: "Phoenix Children’s",
    mission: "Join me in supporting children and families. Every gift, big or small, helps us move forward.",
    photo: { src: "/images/community.jpg", alt: "Placeholder photograph of people joining hands in a gesture of community", position: "center" },
    photoNote: "Community photo · placeholder",
    photoCaption: "Good things happen when we come together.",
    badge: "Small acts.\nBig heart.",
    bottomNote: "One community. One shared goal.",
    scroll: "A little about my why",
  },
  why: {
    eyebrow: "Why I’m taking part",
    title: "Because showing up\nstarts with us.",
    introduction: "Hi, I’m Justin.",
    paragraphs: [
      "I’m Justin, a member of Phoenix Children’s Teen Council. I believe showing up for one another starts with small actions, and I’m inviting my friends, family and community to join me.",
      "You can help by giving an amount that feels right for you or sharing this page. Thank you for being part of it.",
    ],
    quote: "You’re never too young to show up for someone else.",
    signature: "Justin Liang",
    draftLabel: "Draft story · personal message to be finalized",
    photo: { src: "", alt: "Justin Liang, Phoenix Children’s Teen Council member", position: "center" },
    photoPlaceholder: "A face behind\nthe fundraiser.",
    photoPlaceholderNote: "Justin’s photo coming soon",
    photoCaption: "Justin Liang / Teen Council member",
  },
  video: {
    eyebrow: "02 / A personal note",
    title: "A minute with Justin.",
    description: "The reason I’m here, and how you can be part of it.",
    url: "/videos/justin-message-60s.mp4", // Direct MP4/WebM, a YouTube URL, or a Vimeo URL.
    poster: { src: "/images/justin-message.jpg", alt: "Justin sharing his personal fundraising message", position: "center" },
    play: "Play Justin’s message",
    comingSoon: "My video is coming soon",
    placeholderNote: "A personal message from Justin will appear here.",
    duration: "1 minute · A personal message",
    close: "Close video",
    fallback: "Watch the video",
  },
  impact: {
    eyebrow: "03 / What we’re supporting",
    title: "Hope grows\nwhen we give together.",
    description: "Teen Council brings young people together through fundraising, advocacy and volunteering for Phoenix Children’s.",
    learnMore: "Meet the Teen Council",
    learnMoreUrl: "https://phoenixchildrensfoundation.org/giving-groups/pch-teen-council/",
    cards: [
      { icon: "heart", title: "Children & families", text: "Rally around the patients and families at the heart of Phoenix Children’s mission." },
      { icon: "people", title: "Community in action", text: "Turn a circle of friends, family, and neighbors into a community of support." },
      { icon: "sun", title: "The next generation", text: "Encourage young people to lead with empathy, service, and a willingness to help." },
    ],
  },
  fundraising: {
    goal: 1000,
    goalPrompt: "Help me reach my",
    goalLabel: "fundraising goal",
    currency: "USD",
    locale: "en-US",
    eyebrow: "04 / Every bit brings us closer",
    title: "Help me reach my\n{goal} goal.",
    description: "Every gift, big or small, helps us move forward. Choose an amount that feels right for you on my official fundraising page.",
    latestProgress: "See the latest fundraising progress",
    thankYou: "Thank you for being part of my community.",
  },
  thankYouGift: {
    eyebrow: "05 / Made with care",
    title: "A little thank-you, made by me.",
    status: "In planning",
    item: "A 3D-printed keychain",
    companion: "With a personal thank-you card",
    description: "An optional 3D-printed keychain and personal thank-you card.",
    details: "Not available to request yet. Photos and delivery details to follow.",
  },
  share: {
    eyebrow: "06 / A little kindness travels",
    title: "Help spread the word.",
    description: "Share this page with someone who cares. Your support can start a conversation.",
    message: "Help Justin Liang support Phoenix Children’s. Every gift and every share can help bring our community together.",
    emailSubject: "Help Justin support Phoenix Children’s",
    copy: "Copy link", copied: "Link copied!", copyFallback: "Copy this link:",
    email: "Email", text: "Text", linkedin: "LinkedIn",
    qrImage: "/images/justin-fundraiser-qr.png", // Encodes https://my-pch-website.vercel.app/
    qrAlt: "QR code to Justin’s fundraising landing page",
    qrTitle: "Scan to share",
    qrDownload: "Save QR code",
    qrPlaceholder: "QR code\ncoming soon",
    qrCaption: "Open this page on your phone, or save the code to share.",
    allowedSources: ["school", "family", "instagram", "healthcare"],
  },
  footer: {
    line: "A little hope goes a long way.",
    disclosure: "Donations are made directly through Phoenix Children’s official fundraising platform.",
    independence: "This personal fundraising page is independently created by a Teen Council member. It is not an official Phoenix Children’s website.",
    officialLink: "Visit my official fundraiser",
    copyright: "Made with heart, by Justin Liang.",
  },
} as const;
